### PR TITLE
fix pod management can not be canceled

### LINKED ISSUE #568: Pod management can not be canceled
**What happened**:
after I manage traffic in pod level, management can not be canceled
**What you expected to happen**:
management should be canceled
**How to reproduce it (as minimally and precisely as possible)**:
kubectl label pod xxx istio.io/dataplane-mode=kmesh
kubectl label pod xxx istio.io/dataplane-mode-
**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

### PR DESCRIPTION
**Pull request by weli-l**
**What type of PR is this?**
fix pod management can not be canceled

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #568 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/controller/manage/kmesh_manage.go [hunk 1]
```diff
@@ -210,9 +210,6 @@ func shouldEnroll(client kubernetes.Interface, pod *corev1.Pod) bool {
 	if strings.EqualFold(pod.Labels[constants.DataPlaneModeLabel], constants.DataPlaneModeKmesh) {
 		return true
 	}
-	if pod.Annotations[constants.KmeshRedirectionAnnotation] == "enabled" {
```
Comment (hzxuzhonghu) [inline pkg/controller/manage/kmesh_manage.go:213]: @lec-bit This fix would break the secret manager assumption, which heavily rely on this to count numbers

**Comment by hzxuzhonghu** [comment]
@weli-l we should first open pr to main branch, then cherry pick back

File: pkg/controller/manage/kmesh_manage.go (hunk 1 above)
Comment (lec-bit) [reply pkg/controller/manage/kmesh_manage.go:213]: ok，i will test and Modify
