### PR TITLE
Link XDP again in deamon, in order to fix Kmesh has restarted but old XDP program remain linked

### LINKED ISSUE #591: XDP prog fails to update
**What happened**:
Update scenario, when restart kmesh, `XDP` prog is not updated unless restart  managed pods with `kubectl delete -f` and `kubectl apply -f`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
`helm uninstall`, then `helm install` a newer `kmesh` which `XDP` prog is modified
**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

### PR DESCRIPTION
**Pull request by tacslon**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:
Link XDP again in deamon, in order to fix Kmesh has restarted but old XDP program remain linked
**Which issue(s) this PR fixes**:
Fixes #591 #665 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cni/plugin/plugin.go [hunk 1]
```diff
@@ -106,24 +104,24 @@ func getPrevCniResult(conf *cniConf) (*cniv1.Result, error) {
 	return cniv1PrevResult, nil
 }
 
-func enableXdpAuth(ifname string) error {
```
Comment (hzxuzhonghu) [inline pkg/cni/plugin/plugin.go:109]: we should still keep it in cni like manage

File: pkg/bpf/bpf_kmesh_workload.go [hunk 2]
```diff
@@ -458,17 +465,175 @@ func (sm *BpfSendMsgWorkload) Detach() error {
...
+		// Get all NIC iface in a pod
+		ifaces, err := net.Interfaces()
+		if err != nil {
+			return err
+		}
+		log.Infof("Interfaces in pod: %v is: %v", podUID, ifaces)
+
+		// Link XDP prog on every iface, except loopback or not up
+		for _, iface := range ifaces {
+			if iface.Flags&net.FlagLoopback != 0 || iface.Flags&net.FlagUp == 0 {
```
Comment (hzxuzhonghu) [inline pkg/bpf/bpf_kmesh_workload.go:510]: should we exclude linklocal unicast?

File: pkg/bpf/bpf_kmesh_workload.go [hunk 3]
```diff
@@ -458,17 +465,175 @@ func (sm *BpfSendMsgWorkload) Detach() error {
...
+
+	// Update the map
+	xa.rwLock.Lock()
+	defer xa.rwLock.Unlock()
+	xa.podLinkMap[podUID] = podLnInf
+
+	return nil
+}
+
+func (xa *BpfXdpAuthWorkload) UpdatePodLink(podUID types.UID) error {
```
Comment (hzxuzhonghu) [inline pkg/bpf/bpf_kmesh_workload.go:537]: It should be called under the case pod is managed or unmanaged

**Comment by tacslon** [comment]
Try using `link.Update` when kmesh starts

File: pkg/cni/plugin/plugin.go (hunk 1 above)
Comment (tacslon) [reply pkg/cni/plugin/plugin.go:109]: done

File: pkg/bpf/bpf_kmesh_workload.go (hunk 2 above)
Comment (tacslon) [reply pkg/bpf/bpf_kmesh_workload.go:510]: seems there is no corresponding flags in package `net`

File: pkg/bpf/bpf_kmesh_workload.go (hunk 3 above)
Comment (tacslon) [reply pkg/bpf/bpf_kmesh_workload.go]: When a pod is updated from unmanaged to managed, `AddPodLink` will be called, otherwise `DeletePodLink` will be called

**Comment by tacslon** [comment]
The following code can compare if XDP program has any difference with the previous one, but if we always use the previous XDP program, duplicate maps do exist. So for now, always update XDP programs linked at pod's NIC driver.

```
	// If kmesh restarts, prevProgInfo is not nil
	prevProg, prevProgInfo, _ := utils.GetProgAndInfoByName(constants.XDP_PROG_NAME)
	log.Infof("prevProgInfo: %+v", prevProgInfo)
	progTag, _ := spec.Programs[constants.XDP_PROG_NAME].Tag()
	log.Infof("progTag: %v", progTag)
	if prevProgInfo != nil && prevProgInfo.Tag != "" && prevProgInfo.Tag == progTag {
		// Same XDP prog, just assign, do not load new prog, but use new maps to prevent duplicate maps
		xa.XdpShutdown = prevProg
		if xa.MapOfAuth, err = utils.GetMapByName(constants.XDP_MAP_NAME); err != nil {
			return nil, err
		}
		log.Infof("MapOfAuth: %+v", xa.MapOfAuth)
	} else {
		// New prog, do load and assignment
		if err = spec.LoadAndAssign(&xa.KmeshXDPAuthObjects, &opts); err != nil {
			return nil, err
		}
	}
```

**Comment by hzxuzhonghu** [comment]
> but if we always use the previous XDP program, duplicate maps do exist

Where do we create the duplicate maps again?

**Comment by tacslon** [comment]
> > but if we always use the previous XDP program, duplicate maps do exist
> 
> Where do we create the duplicate maps again?

Other eBPF programs that have reference to same maps, e.g. `sockops` has a reference to `bpf_log_level`, and old XDP program has an old `bpf_log_level` map

File: pkg/controller/manage/manage_controller.go [hunk 4]
```diff
@@ -64,6 +68,23 @@ type KmeshManageController struct {
 	client            kubernetes.Interface
 }
 
+type podEventArgs struct {
```
Comment (hzxuzhonghu) [inline pkg/controller/manage/manage_controller.go:71]: donot do this kind of refactor in this bug fix, otherwise it is a little bit hard to review

File: pkg/controller/manage/manage_controller.go [hunk 5]
```diff
@@ -337,3 +386,39 @@ func sendCertRequest(security *kmeshsecurity.SecretManager, pod *corev1.Pod, op
...
+	if err := netns.WithNetNSPath(netNsPath, func(netns.NetNS) error {
+		// Get all NIC iface in a pod
+		ifaces, err := net.Interfaces()
+		if err != nil {
+			return err
+		}
+
+		// Link XDP prog on every iface, except loopback or not up
+		for _, iface := range ifaces {
+			if iface.Flags&net.FlagLoopback != 0 || iface.Flags&net.FlagUp == 0 {
```
Comment (hzxuzhonghu) [inline pkg/controller/manage/manage_controller.go:405]: Please take a look at how istio get proxy ip

```
for _, iface := range ifaces {
		if iface.Flags&net.FlagUp == 0 {
			continue // interface down
		}
		if iface.Flags&net.FlagLoopback != 0 {
			continue // loopback interface
		}
		addrs, _ := iface.Addrs()

		for _, addr := range addrs {
			var ip net.IP
			switch v := addr.(type) {
			case *net.IPNet:
				ip = v.IP
			case *net.IPAddr:
				ip = v.IP
			default:
				continue
			}
			ipAddr, okay := netip.AddrFromSlice(ip)
			if !okay {
				continue
			}
			// unwrap the IPv4-mapped IPv6 address
			unwrapAddr := ipAddr.Unmap()
			if !unwrapAddr.IsValid() || unwrapAddr.IsLoopback() || unwrapAddr.IsLinkLocalUnicast() || unwrapAddr.IsLinkLocalMulticast() {
				continue
			}
			if unwrapAddr.IsUnspecified() {
				ok = false
				continue
			}
			ipAddresses = append(ipAddresses, unwrapAddr.String())
		}
	}
```

**Comment by hzxuzhonghu** [comment]
> > but if we always use the previous XDP program, duplicate maps do exist
> 
> Where do we create the duplicate maps again?

>Other eBPF programs that have reference to same maps, e.g. `sockops` has a reference to `bpf_log_level`, and old XDP program has an old `bpf_log_level` map

I am not sure i understand what you mean. Do you mean  sockops refer a bpf_log_level map, but xdp refer another? How could that happen if we detach and unlink the old xdp prog correctly

**Comment by hzxuzhonghu** [comment]
You should respect the `restart` feature, do re attach/link as other bpf prog

File: pkg/controller/manage/manage_controller.go (hunk 4 above)
Comment (tacslon) [reply pkg/controller/manage/manage_controller.go]: done, will be edited in next PR

File: pkg/controller/manage/manage_controller.go [hunk 6]
```diff
@@ -225,6 +228,7 @@ func enableKmeshManage(pod *corev1.Pod, queue workqueue.RateLimitingInterface, s
 		return
 	}
 	queue.AddRateLimited(QueueItem{podName: pod.Name, podNs: pod.Namespace, action: ActionAddAnnotation})
+	linkXdp(nspath, xdpProgFd, mode)
```
Comment (hzxuzhonghu) [inline pkg/controller/manage/manage_controller.go:231]: should add a unlink op in `disableKmeshManage`

**Comment by hzxuzhonghu** [comment]
lgtm otherwise

File: pkg/controller/manage/manage_controller.go (hunk 6 above)
Comment (tacslon) [reply pkg/controller/manage/manage_controller.go]: done

File: pkg/controller/manage/manage_controller.go [hunk 7]
```diff
@@ -337,3 +343,79 @@ func sendCertRequest(security *kmeshsecurity.SecretManager, pod *corev1.Pod, op
...
+			ifLink, err := netlink.LinkByName(iface.Name)
+			if err != nil {
+				return err
+			}
+			// Detach by using netlink since pin doesn't exist
+			if err := netlink.LinkSetXdpFdWithFlags(ifLink, -1, int(link.XDPGenericMode)); err != nil {
+				return fmt.Errorf("detaching generic-mode XDP program using netlink: %w", err)
+			}
+
+			if err := netlink.LinkSetXdpFdWithFlags(ifLink, -1, int(link.XDPDriverMode)); err != nil {
```
Comment (hzxuzhonghu) [inline pkg/controller/manage/manage_controller.go:410]: why `XDPDriverMode` and `XDPGenericMode` needed

Comment (tacslon) [reply pkg/controller/manage/manage_controller.go:410]: reference to cilium's XDP detach, because we do not know which mode(Driver or Generic) the XDP is linked

**Comment by hzxuzhonghu** [comment]
@YaoZengzeng TestRemoveAddNsOrServiceWaypoint failed

**Comment by LiZhenCheng9527** [comment]
> @YaoZengzeng TestRemoveAddNsOrServiceWaypoint failed

The PR I merged in yesterday also failed, but rerunning the job passed it.

**Comment by YaoZengzeng** [comment]
> @YaoZengzeng TestRemoveAddNsOrServiceWaypoint failed

I'll take a closer look

**Comment by YaoZengzeng** [comment]
It seems like that the Kmesh daemon crashed during the test, casuing the newly deployed waypoint fail to take effect.

**Comment by hzxuzhonghu** [comment]
Ut coverage does not satisfy the checker

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
