### PR TITLE
Fix cgroup_skb/* get sk_storage failed

### LINKED ISSUE #1348: Unexpected log from `cgroup_skb`
**What happened**:

```
time="2025-04-28T03:03:23Z" level=info msg="[PROBE] ERR: on data: bpf_sk_storage_get failed\n" subsys=ebpf
time="2025-04-28T03:03:23Z" level=info msg="[PROBE] ERR: on data: bpf_sk_storage_get failed\n" subsys=ebpf

```

This is the complete logs from kmesh while a httpbin pod restarted

```

time="2025-04-28T03:09:46Z" level=info msg="default/httpbin-55ffdcd94-4hsfr: enable Kmesh manage" subsys=manage_controller
time="2025-04-28T03:09:46Z" level=info msg="[PROBE] ERR: on data: bpf_sk_storage_get failed\n" subsys=ebpf
time="2025-04-28T03:09:46Z" level=info msg="add annotation for pod default/httpbin-55ffdcd94-4hsfr" subsys=manage_controller
time="2025-04-28T03:09:46Z" level=info msg="[PROBE] ERR: on data: bpf_sk_storage_get failed\n" subsys=ebpf
time="2025-04-28T03:09:46Z" level=info msg="[AUTH] ERR: xdp: auth offloaded" subsys=ebpf
time="2025-04-28T03:09:47Z" level=info msg="[AUTH] ERR: xdp: auth offloaded" subsys=ebpf
time="2025-04-28T03:09:47Z" level=info msg="default/httpbin-55ffdcd94-ls8gg: enable Kmesh manage" subsys=manage_controller
time="2025-04-28T03:09:47Z" level=info msg="[PROBE] ERR: on data: bpf_sk_storage_get failed\n" subsys=ebpf
time="2025-04-28T03:09:47Z" level=info msg="add annotation for pod default/httpbin-55ffdcd94-ls8gg" subsys=manage_controller
time="2025-04-28T03:09:47Z" level=info msg="default/httpbin-55ffdcd94-4hsfr: Pod managed by Kmesh is deleted" subsys=manage_controller
time="2025-04-28T03:09:48Z" level=info msg="[AUTH] ERR: xdp: auth offloaded" subsys=ebpf
time="2025-04-28T03:09:49Z" level=info msg="[AUTH] ERR: xdp: auth offloaded" subsys=ebpf

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1348

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
cc @yp969803 

@Kuromesi

**Comment by yp969803** [comment]
have u checked it locally, using bpf logs, it is better if we check the stuffs locally before merging to prevent bugs.
you can use this manifest to simulate long connection
```
apiVersion: v1
kind: Pod
metadata:
  name: ws-server
  labels:
    app: ws-server
spec:
  containers:
  - name: ws-server
    image: node:18
    command: ["/bin/sh", "-c"]
    args:
      - |
        mkdir server 
        cd server 
        npm init -y
        npm install ws
        cat << EOF > server.js
        const WebSocket = require('ws');
        const server = new WebSocket.Server({ port: 8080 });
        server.on('listening', () => {
          console.log('🚀 WebSocket server started on ws://localhost:8080');
        });

        server.on('connection', socket => {
          console.log('Client connected');
          
          // Send data every 1 seconds
          setInterval(() => {
            socket.send(`Hello world`);
            console.log('Sent message to client');
          }, 1000);

          socket.on('message', message => {
            console.log(`Received`);
          });

          socket.on('close', () => {
            console.log('Client disconnected');
          });
        });
        EOF
        node server.js

    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ws-server-service
  labels:
    app: ws-server
spec:
  selector:
    app: ws-server
  ports:
  - protocol: TCP
    port: 8080        # Port exposed by the service
    targetPort: 8080  # Port the server container listens on

--- 

apiVersion: v1
kind: Pod
metadata:
  name: ws-client
  labels:
    app: ws-client
spec:
  containers:
  - name: ws-client
    image: node:18
    command: ["/bin/sh", "-c"]
    args:
      - |
        mkdir client
        cd client
        npm init -y
        npm install ws 
        cat <<EOF > client.js
        const WebSocket = require('ws');
        const socket = new WebSocket('ws://ws-server-service.default.svc.cluster.local:8080');

        socket.on('open', () => {
          console.log('Connected to server');
          socket.send('Hello from client');
          console.log('Sent message to server');
        });

        socket.on('message', data => {
          console.log(`Received`);

        });

        socket.on('close', () => {
          console.log('Connection closed');
        });
        EOF
        node client.js

```

**Comment by hzxuzhonghu** [comment]
what do you mean?

/retest

**Comment by yp969803** [comment]
i was just asking if u have checked it locally, does the normal packets reaching to the observed_data function

**Comment by hzxuzhonghu** [comment]
I am not sure if kmesh restart would influence the long connection metric. For this patch, it does not bring regression for long connection

File: bpf/include/bpf_common.h [hunk 1]
```diff
@@ -260,6 +260,23 @@ static inline void remove_kmesh_managed_ip(__u32 family, __u32 ip4, __u32 *ip6)
         BPF_LOG(ERR, KMESH, "remove ip failed, err is %d\n", err);
 }
 
+static inline bool sock_conn_from_sim(struct __sk_buff *skb)
+{
+    __u16 enable_port = ENABLE_KMESH_PORT;
+    __u16 disable_port = DISABLE_KMESH_PORT;
+    __u16 dst_port = (__u16)(skb->remote_port >> 16);
+    if (bpf_ntohs(dst_port) != enable_port && bpf_ntohs(dst_port) != disable_port)
```
Comment (nlgwcy) [inline bpf/include/bpf_common.h:268]:
```suggestion
    if (bpf_ntohs(dst_port) != ENABLE_KMESH_PORT && bpf_ntohs(dst_port) != DISABLE_KMESH_PORT)
```

**Comment by hzxuzhonghu** [comment]
@nlgwcy Another look
