### PR TITLE
fix bpf-map test failed

### LINKED ISSUE #340: Failed to run cluster_test.go
**What happened**:
go test failed
```sh
[root@k8s-master v2]# go test -bench=. --benchtime=100x
time="2024-05-18T23:23:56+08:00" level=error msg="loadKmeshSockConnObjects failed: field CgroupConnect4Prog: program cgroup_connect4_prog: map map_of_manager: map create: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" subsys=pkg/bpf
goos: linux
goarch: amd64
pkg: kmesh.net/kmesh/pkg/cache/v2
cpu: 12th Gen Intel(R) Core(TM) i7-1260P
BenchmarkClusterFlush-16        time="2024-05-18T23:23:56+08:00" level=error msg="loadKmeshSockConnObjects failed: field CgroupConnect4Prog: program cgroup_connect4_prog: map map_of_manager: map create: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" subsys=pkg/bpf
       0                       NaN ns/op
time="2024-05-18T23:23:56+08:00" level=error msg="loadKmeshSockConnObjects failed: field CgroupConnect4Prog: program cgroup_connect4_prog: map map_of_manager: map create: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" subsys=pkg/bpf
BenchmarkFlush-16               time="2024-05-18T23:23:56+08:00" level=error msg="loadKmeshSockConnObjects failed: field CgroupConnect4Prog: program cgroup_connect4_prog: map map_of_manager: map create: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" subsys=pkg/bpf
       0                       NaN ns/op
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
main
- Others:

### PR DESCRIPTION
**Pull request by nlgwcy**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #340 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/utils/test/bpf_map.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ import (
 	"syscall"
 	"testing"
 
+	"github.com/cilium/ebpf/rlimit"
```
Comment (LiZhenCheng9527) [inline pkg/utils/test/bpf_map.go:25]: A blank line is needed here to distinguish the third-party kpg from Kmesh's pkg

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
@LiZhenCheng9527 can we run the bench in the ci

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
