### PR TITLE
fix(ipsec): resolve golint warnings and remove name stuttering

### LINKED ISSUE #1475: golint warnings in ipsec_controller.go
**What would you like to be added**:
golint warnings in ipsec_controller.go needs to be fixed:

Image

**Why is this needed**:
to ensure the codebase follows Go best practices

### PR DESCRIPTION
**Pull request by shivansh-gohem**
This PR resolves golint warnings in `pkg/controller/encryption/ipsec/ipsec_controller.go` to improve code quality and comply with Go best practices.

**Changes:**
1. **Removed Stuttering:** Renamed `IPSecController` to `Controller` and `NewIPsecController` to `NewController`. Since this resides in the `ipsec` package, usage becomes `ipsec.Controller` instead of the repetitive `ipsec.IPSecController`.
2. **Standardization:** Updated `ClusterId` -> `ClusterID` and `PodIp` -> `PodIP` to match Go naming conventions.
3. **Documentation:** Added missing GoDoc comments for exported functions (`NewController`, `Run`, `Stop`, `CleanAllIPsec`).
4. **Refactoring:** Updated `ipsec_controller_test.go` and `pkg/controller/controller.go` to reflect the renaming changes.

**Verification:**
Ran `golangci-lint run --build-tags=linux pkg/controller/encryption/ipsec/...` locally. Verified that all linting errors (typecheck and style) related to this controller are resolved.

Fixes #1475

### CODE REVIEW

**Comment by shivansh-gohem** [comment]
Thanks for the review! You are right that the error handling here is missing.

However, since this PR focuses strictly on linting and renaming (to fix #1475), I prefer not to change the function signature or logic right now. This avoids "scope creep" and prevents breaking the reflection-based tests in ipsec_controller_test.go.

I can address the error handling in a separate, follow-up PR

File: config/kmesh_marcos_def.h [hunk 1]
```diff
@@ -7,22 +7,22 @@
  * loopback address link conflicts. Obtains the namespace cookie of the
  * current container based on the bpf_get_netns_cookie auxiliary function.
  */
-#define MDA_LOOPBACK_ADDR 1
+#define MDA_LOOPBACK_ADDR 0
```
Comment (LiZhenCheng9527) [inline config/kmesh_marcos_def.h]: Why change this?

**Review by LiZhenCheng9527 — COMMENTED** [review]
I'm not quite sure what the point is in you making these changes.

File: config/kmesh_marcos_def.h (hunk 1 above)
Comment (shivansh-gohem) [reply config/kmesh_marcos_def.h]: My apologies. These changes were automatically generated by the build script based on my local kernel environment and were included by mistake. I will revert the file so that PR will now only contain the intended linting fixes!

File: pkg/controller/encryption/ipsec/ipsec_controller.go [hunk 2]
```diff
@@ -61,7 +62,8 @@ type lpmKey struct {
 	ip     [4]uint32
 }
 
-type IPSecController struct {
+// Controller manages the IPsec configuration and synchronization for Kmesh.
+type Controller struct {
```
Comment (LiZhenCheng9527) [inline pkg/controller/encryption/ipsec/ipsec_controller.go:66]: I still have some confusion. Why is this change needed? Is there something wrong with the name `IPSecController`?

Comment (shivansh-gohem) [reply pkg/controller/encryption/ipsec/ipsec_controller.go:66]: The renaming from `IPSecController` to `Controller` addresses a `golint` warning regarding "stuttering."

Since this struct resides within the `ipsec` package, Go naming conventions suggest avoiding the repetition of the package name in the type name.

* **Before:** `ipsec.IPSecController` (Redundant repetition)
* **After:** `ipsec.Controller` (Clean and idiomatic)

This change aligns the codebase with standard Go style guidelines without altering any logic.

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
