### PR TITLE
Fix CI workflow and fix golint issues

### LINKED ISSUE #54: Add CI Checks
This is an umbrella issue for CI tasks.
There are many checks we should make in CI

- [ ] Boilerplate header check
- [ ] Lint check
- [ ] Build
- [ ] Unit test
- [ ] Integration test

### PR DESCRIPTION
**Pull request by VanderChen**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
1. Adapt CI workflows to the current version.
2. Fix some golint issues, including import order and unused function codes.

**Which issue(s) this PR fixes**:
Fixes #54 

**Special notes for your reviewer**:

There are unused function codes in the existing code, which will cause the golint check to fail. Due to possible future use, comment them out rather than delete them for now.

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/bpf/pin.go [hunk 1]
```diff
@@ -59,24 +59,26 @@ func unpinPrograms(value *reflect.Value) error {
...
-		if err := tp.Pin(path + info.Name); err != nil {
-			return fmt.Errorf("pin map failed, %s", err)
-		}
-	}
-
-	return nil
-}
+// Due to the golint issuse, comment unused functions temporaryly
+
+// func pinMaps(value *reflect.Value, path string) error {
```
Comment (hzxuzhonghu) [inline pkg/bpf/pin.go:64]: @nlgwcy Do we plan to use them

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
