### PR TITLE
fix getKmeshWaypointImage tag

### LINKED ISSUE #1287: kmeshctl waypoint generate wrong proxyImage tag
**What happened**:

```
kmeshctl waypoint generate -n default

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    sidecar.istio.io/proxyImage: ghcr.io/kmesh-net/waypoint:vv1.0.0 
  name: waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
```

**What you expected to happen**:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    sidecar.istio.io/proxyImage: ghcr.io/kmesh-net/waypoint:v1.0.0
  name: waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
client version: v1.0.0-44069d88ffd77e8be3aa81f890fd37f0f02a51f7

- Kmesh version: 
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by silenceper**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1287 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: ctl/waypoint/waypoint.go [hunk 1]
```diff
@@ -630,6 +630,8 @@ func getKmeshWaypointImage() string {
 	}
 
 	ver := version.Get().GitVersion
+	// if ver prefix with v, remove it
+	ver = strings.TrimPrefix(ver, "v")
 
 	return fmt.Sprintf("ghcr.io/kmesh-net/waypoint:v%s", ver)
```
Comment (YaoZengzeng) [inline ctl/waypoint/waypoint.go:636]: @silenceper thanks for your contribution!

But why not remove the `v` here?

Comment (silenceper) [reply ctl/waypoint/waypoint.go:636]: I am not sure whether GitVersion will eventually have the v prefix. If it does not, it will be compatible.

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
