### PR TITLE
fix file non-existent error when kmesh start with --enable-ipsec=true

### LINKED ISSUE #1289: Kmesh cannot start when --enable-ipsec=true and no IPsec pre-shared keys set by kmeshctl
**What happened**:
Kmesh cannot start when `--enable-ipsec=true` and no IPsec pre-shared keys set by `kmeshctl`.

**What you expected to happen**:
Kmesh should start properly even if no IPsec pre-shared keys is set.

**How to reproduce it (as minimally and precisely as possible)**:
Start Kmesh with  `--enable-ipsec=true` and do not set IPsec pre-shared keys by `kmeshctl`.

**Anything else we need to know?**:
Log output:
```
[root@Aero15 kmesh]# k logs -f -n kmesh-system kmesh-gzwks
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --bpf-fs-path=\"/sys/fs/bpf\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --cgroup2-path=\"/mnt/kmesh_cgroup2\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --cni-etc-path=\"/etc/cni/net.d\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --conflist-name=\"\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --enable-bypass=\"false\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --enable-ipsec=\"true\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --enable-mda=\"false\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --enable-secret-manager=\"false\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --help=\"false\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --mode=\"dual-engine\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --monitoring=\"true\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --plugin-cni-chained=\"true\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="FLAG: --profiling=\"false\"" subsys=manager
time="2025-03-28T03:14:43Z" level=info msg="kmesh start with Normal" subsys=bpf
time="2025-03-28T03:14:45Z" level=info msg="bpf loader start successfully" subsys=manager
time="2025-03-28T03:14:45Z" level=info msg="cleaned kmesh_version map" subsys=bpf
time="2025-03-28T03:14:45Z" level=info msg="cleanup bpf map success" subsys=bpf
Error: failed to new IPsec controller, failed to load ipsec key from file ./kmesh-ipsec/ipSec: load ipsec keys failed: open ./kmesh-ipsec/ipSec: no such file or directory
time="2025-03-28T03:14:45Z" level=error msg="failed to new IPsec controller, failed to load ipsec key from file ./kmesh-ipsec/ipSec: load ipsec keys failed: open ./kmesh-ipsec/ipSec: no such file or directory" subsys=main
Error: parse BpfConfig failed, stat /mnt/kmesh_cgroup2: no such file or directory
time="2025-03-28T03:14:45Z" level=error msg="parse BpfConfig failed, stat /mnt/kmesh_cgroup2: no such file or directory" subsys=main
kmesh exit
```

**Environment**:

- Kmesh version: https://github.com/kmesh-net/kmesh/commit/3a81bcc6773a42a37621c912c42523be70799207
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`): Dual-Engine Mode
- Istio version: v1.24.0
- Kernel version: 5.15
- Others:

### PR DESCRIPTION
**Pull request by zrggw**
**What type of PR is this?**
/kind bug
/kind enhancement

**What this PR does / why we need it**:
When kmesh starts, if you set `--enable-ipsec=true`, it will report errors during initialization of the ipsec controller because it reads non-existent file. Add a check for whether the file exists before reading the file.

**Which issue(s) this PR fixes**:

Fixes #1289

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zrggw** [comment]
cc @hzxuzhonghu

**Comment by LiZhenCheng9527** [comment]
In my opinion, We shoudld add a `create` sub command in `kmeshctl secret` or add `kmeshctl ipsec create` to create a secret for IPsec. Such command return the created secret namespacedName. Choose between automatic creation or manual creation for user.

File: pkg/controller/encryption/ipsec/ipsec_handler.go [hunk 1]
```diff
@@ -30,13 +32,21 @@ import (
...
 
 	"kmesh.net/kmesh/pkg/constants"
+	"kmesh.net/kmesh/pkg/kube"
 	"kmesh.net/kmesh/pkg/kube/apis/kmeshnodeinfo/v1alpha1"
 )
 
 const (
-	IpSecKeyFile = "./kmesh-ipsec/ipSec"
+	IpSecKeyFile      = "./kmesh-ipsec/ipSec"
+	SecretName        = "kmesh-ipsec"
```
Comment (LiZhenCheng9527) [inline pkg/controller/encryption/ipsec/ipsec_handler.go]: Is there a way to return the name of the automatically created secret to the user?
If it is deleted, do we have a mechanism to ensure the secret is recreated? Or is it necessary to restart the kmesh-daemon to regenerate the secret?

File: pkg/controller/encryption/ipsec/ipsec_handler.go [hunk 2]
```diff
@@ -396,3 +407,38 @@ func (is *IpSecHandler) Flush() error {
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name: SecretName,
+		},
+		Type: v1.SecretTypeOpaque,
+		Data: map[string][]byte{
+			"ipSec": secretData,
+		},
+	}
+	_, err = k8sClientSet.CoreV1().Secrets(kube.KmeshNamespace).Get(context.TODO(), SecretName, metav1.GetOptions{})
+	if err != nil {
```
Comment (LiZhenCheng9527) [inline pkg/controller/encryption/ipsec/ipsec_handler.go]: Add a handling branch for the `notfound`.
Only resource notfond, you can use `create` to create a new resource. If it is exist, you should use `update`.

File: pkg/controller/encryption/ipsec/ipsec_handler.go (hunk 1 above)
Comment (zrggw) [reply pkg/controller/encryption/ipsec/ipsec_handler.go]: We can monitor whether the secret file is deleted in the StartWatch function. If the file does not exist, we call initConfig to recreate it.

Comment (zrggw) [reply pkg/controller/encryption/ipsec/ipsec_handler.go]: Perhaps we can record the created SecretName in the logs, and view the SecretName through commands such as `kemshctl secret ipsec --show`.

**Comment by hzxuzhonghu** [comment]
>Added an initConfig function in the ipsec handler.

>The initConfig function generates a default IPsecKey when initializing the controller.
In the NewIPsecController function, loading this file may fail, but it will still be read later in the StartWatch function.

I am not sure why not waiting until the secret mounted rather than generating an useless key

**Comment by zrggw** [comment]
> > Added an initConfig function in the ipsec handler.
> 
> > The initConfig function generates a default IPsecKey when initializing the controller.
> > In the NewIPsecController function, loading this file may fail, but it will still be read later in the StartWatch function.
> 
> I am not sure why not waiting until the secret mounted rather than generating an useless key

To avoid an error (#1289) during IPSec controller initialization, the `./kmesh-ipsec/ipsec` file (which contains the necessary keys like SPI, aeadKeyName, aeadKey, etc.) must be present. If you did not use `kmeshctl secret` to generate this file before starting kmesh, althrough secret kmesh-ipsec will be mounted, but secret kmesh-ipsec secret hasn't been created but `./kmesh-ipsec/ipsec` is missing,  so using initConfig to create secret kmesh-ipsec which has ipSec in Secret.Data(so ./kemsh/kmesh-ipsec/ipSec file will be created and can be readed).

**Comment by zrggw** [comment]
I understand, so is there no need to add IPsec configuration when enabling --enable-ipsec=true during kmesh startup? And only let `kmeshctl` to mange ipsec secret? @hzxuzhonghu

**Comment by zrggw** [comment]
I was thinking maybe we can optimize the secret part of kmeshctl related to IPsec and design the command as `kmeshctl secret [command] [flags]`.

1. kmeshctl secret create // Create a secret configuration for IPsec, using a random key
2. kmeshctl secret create --key $(user_specified_key) // Create a secret configuration for IPsec, using a user-specified key
3. kmeshctl secret get // Get the secret information in the kmesh-system namespace
4. kmeshctl secret delete // Delete the secret in the kmesh-system namespace

Currently, all these operations are performed by default on the kmesh-ipsec secret.
@hzxuzhonghu @LiZhenCheng9527
