### PR TITLE
fix hash name bug (#479)

### LINKED ISSUE #479: HashName can output different hash value for same str
HashName.StrToNum can allocate different hash value to a str when some previous allocated values not used anymore

### PR DESCRIPTION
**Pull request by Okabe-Rintarou-0**
**What type of PR is this?**
bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #479 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/controller/workload/workload_hash.go [hunk 1]
```diff
@@ -25,25 +25,38 @@ var (
 	hash = fnv.New32a()
 )
 
+const tombstoneMarker = "\x00"
+
 // HashName converts a string to a uint32 integer as the key of bpf map
 type HashName struct {
 	numToStr map[uint32]string
+	// records its tombstone number given a string
+	tombstones map[string]uint32
```
Comment (hzxuzhonghu) [inline pkg/controller/workload/workload_hash.go:34]: This is kind of mem leak. Our requirement is:

1. a str should be allocated with a consistent value
2. after it deleted, and then at some time recreated, the value can be different.
3. It's better to be consistent for the case that kmesh daemon restart, which seems difficult with this implement. Maybe we can persist the maps somewhere.

Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:34]: > 2\. after it deleted, and then at some time recreated, the value can be different.

Requirement 1 means for a str like "foo", if we call StrToNum we will get number 123. Then at anytime we StrToNum("foo") should always get 123? Even if collision happened?
Can you give an example about requirement 2?

Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:34]: In the original implemention, there exists another problem.
If A collides with B.
If StrToNum(A) = 123, then StrToNum(B) = 124
Then we delete A, we will delete numToStr[123].
Then we delete B, we will also delete numToStr[123], cause Delete will call StrToNum, where StrToNum(B) will be 123, if A is deleted(since there is no collision any more). In this case, we will leave numToStr[124] = B, which is also a kind of mem leak.

Comment (hzxuzhonghu) [reply pkg/controller/workload/workload_hash.go:34]: >after it deleted, and then at some time recreated, the value can be different.


say `foo` at t0 is allcated `1234`, then at t1, it is deleted. In our case, all the info is deleted from bpf map.

Maybe t2, `foo` is recreated, then we can allocate it to `2345`.  It need to be consistent during its lifecycle.

Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:34]: I got it. We need to persist the numtostr map in case kmesh restarts.

Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:34]: > In the original implemention, there exists another problem. If A collides with B. If StrToNum(A) = 123, then StrToNum(B) = 124 Then we delete A, we will delete numToStr[123]. Then we delete B, we will also delete numToStr[123], cause Delete will call StrToNum, where StrToNum(B) will be 123, if A is deleted(since there is no collision any more). In this case, we will leave numToStr[124] = B, which is also a kind of mem leak.

to solve this problem, we will still need the  tombstone marker

Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:34]: We only need to store string that cause collision.
For example, if A collides with B.
We call StrToNum(A), then StrToNum(B).
A got "123", B got "124"
We only need to persist (B, 124). Since after restart, we call StrToNum(B) we can get StrToNum(B) = 124 from persisted map. And StrToNum(A) = 123 according to hash value.

File: pkg/controller/workload/workload_hash.go [hunk 2]
```diff
@@ -42,12 +78,20 @@ func (h *HashName) StrToNum(str string) uint32 {
...
 	for num = hash.Sum32(); num < math.MaxUint32; num++ {
-		if h.numToStr[num] == "" {
+		// Create a new item if we find an empty slot
+		if _, exists := h.numToStr[num]; !exists {
 			h.numToStr[num] = str
-			break
-		} else if h.numToStr[num] == str {
+			h.strToNum[str] = num
+			// Create a new item here, should flush
+			if err := h.flush(); err != nil {
```
Comment (hzxuzhonghu) [inline pkg/controller/workload/workload_hash.go:92]: Can we write delta data? Flush all seems very expensive

File: pkg/controller/workload/workload_hash.go [hunk 3]
```diff
@@ -42,12 +78,20 @@ func (h *HashName) StrToNum(str string) uint32 {
 	hash.Reset()
 	hash.Write([]byte(str))
 
+	if num, exits := h.strToNum[str]; exits {
+		return num
+	}
+
 	// Using linear probing to solve hash conflicts
 	for num = hash.Sum32(); num < math.MaxUint32; num++ {
```
Comment (hzxuzhonghu) [inline pkg/controller/workload/workload_hash.go:86]: not related to your code。

If num overflows, should we iterate from 0

File: pkg/controller/workload/workload_hash.go (hunk 2 above)
Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:92]: Sure. What about appending?

File: pkg/controller/workload/workload_hash.go (hunk 3 above)
Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:86]: I think it's necessary. It should be a ring.

File: pkg/controller/workload/workload_hash.go (hunk 2 above)
Comment (Okabe-Rintarou-0) [reply pkg/controller/workload/workload_hash.go:92]: > maybe yaml is simpler
> 
> ```
> foo: 123
> bar: 124
> ```

right, that's a better idea.

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

we can use the pkg `sigs.k8s.io/yaml`, which is from k8s ecosystem
