### PR TITLE
Fixed bug in bpf where IPv4 destination address was stored as IPv6

### LINKED ISSUE #653: Does not pewrform when using tcp-echo to test the l4 authorizationPolicy
**What happened**:
When using tcp-echo to test the l4 authorizationPolicy, it does not perform the relevant actions.

I added the following configuration:
```console
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-by-tcp-echo 
 namespace: default
spec:
 selector:
   matchLabels:
     app: tcp-echo
 action: ALLOW
 rules:
 - from:
   - source:
       ipBlocks:
       - 10.244.0.118
```

I got:
```console
kubectl exec sleep-bc9998558-w4nf4 -- sh -c 'echo "port 9000" | nc tcp-echo 9000' | grep "hello" && echo 'connection succeeded' || echo 'connection rejected'
hello port 9000
connection succeeded
```
No logs for auth deny.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:  
- Kmesh version: 0.4.0-release
- Others: 5.15.0-102-generic

### PR DESCRIPTION
**Pull request by LiZhenCheng9527**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #653 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: bpf/kmesh/workload/sockops.c [hunk 1]
```diff
@@ -38,8 +38,12 @@ static inline bool is_managed_by_kmesh(struct bpf_sock_ops *skops)
     struct manager_key key = {0};
     if (skops->family == AF_INET)
         key.addr.ip4 = skops->local_ip4;
-    if (skops->family == AF_INET6)
-        IP6_COPY(key.addr.ip6, skops->local_ip6);
+    if (skops->family == AF_INET6) {
+        if (is_ipv4_mapped_addr(skops->local_ip6))
+            key.addr.ip4 = skops->local_ip4;
```
Comment (hzxuzhonghu) [inline bpf/kmesh/workload/sockops.c:43]: is skops->local_ip4 and skops->local_ip6 set simutaneously?

File: bpf/kmesh/workload/sockops.c [hunk 2]
```diff
@@ -56,14 +60,28 @@ static inline void extract_skops_to_tuple(struct bpf_sock_ops *skops, struct bpf
...
+    if (skops->family == AF_INET6) {
         bpf_memcpy(tuple_key->ipv6.saddr, skops->local_ip6, IPV6_ADDR_LEN);
         bpf_memcpy(tuple_key->ipv6.daddr, skops->remote_ip6, IPV6_ADDR_LEN);
         // local_port is host byteorder, need to htons
         tuple_key->ipv6.sport = bpf_htons(GET_SKOPS_LOCAL_PORT(skops));
         // remote_port is network byteorder
         tuple_key->ipv6.dport = GET_SKOPS_REMOTE_PORT(skops);
     }
+
+    if (is_ipv4_mapped_addr(tuple_key->ipv6.daddr)) {
```
Comment (hzxuzhonghu) [inline bpf/kmesh/workload/sockops.c:73]: I doubt this is not right. If the dst address is mapped address.  Assume you want to extract to ipv4, i am not sure why operating on ip6 below, since is it a union of ipv4 and ipv6.

And BTW, since the family == AF_INET6, how can we make it work when we dnat to v4?

Can you test with a real example

File: pkg/auth/rbac.go [hunk 3]
```diff
@@ -480,7 +482,10 @@ func (r *Rbac) buildConnV6(buf *bytes.Buffer) (rbacConnection, error) {
 		conn.dstIp = binary.BigEndian.AppendUint32(conn.dstIp, tupleV6.DstAddr[i])
 	}
 	conn.dstPort = uint32(tupleV6.DstPort)
+	// conn.dstIp = restoreIPv4(conn.dstIp)
+	// conn.srcIp = restoreIPv4(conn.srcIp)
```
Comment (hzxuzhonghu) [inline pkg/auth/rbac.go:486]: remove

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Comment by hzxuzhonghu** [comment]
Should be backported
