### PR TITLE
Resolving communication issue between pods after enabling IPsec

### LINKED ISSUE #1481: Some issues encountered in writing Ipsec E2E tests
I followed the steps below to deploy kmesh with ipsec enabled：
1.`kmeshctl secret --key=$(dd if=/dev/urandom count=36 bs=1 2>/dev/null | xxd -p -c 64)`
2.`kubectl apply -f ./kmesh/deploy/yaml/crd/kmesh.net_kmeshnodeinfos.yaml`
3.`kubectl apply -f ./kmesh/deploy/yaml/`
` [
  "./start_kmesh.sh --mode=dual-engine --enable-bypass=false --enable-ipsec=true",
]`
4.`kubectl label namespace default istio.io/dataplane-mode=Kmesh`
`kubectl apply -f ./kmesh/samples/httpbin/httpbin.yaml` with     nodeName: kmesh-testing-worker
`kubectl apply -f ./kmesh/samples/sleep/sleep.yaml`    with  nodeName: kmesh-testing-control-plane

In the sleep pod，curl  ip + port of the httpbin service would fail, while kmesh reported an error:
`time="2025-08-12T11:00:52Z" level=error msg="grpc reconnect failed, create workload stream failed, DeltaAggregatedResources failed, rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.96.95.184:15012: i/o timeout\"" subsys=controller`

curl the ip + port of the httpbin pod would succeed. The ESP package can be seen in the docker container of the kind cluster.

Then I run E2E test script with ipsec enabled. The modifications I made are as follows:
1.add volume and volumount
`  - mountPath: /kmesh/kmesh-ipsec
    name: kmesh-ipsec`

`  - name: kmesh-ipsec
    secret:
    secretName: kmesh-ipsec
    optional: true` in daemonset.yaml
2.add clusterrole apigroups
`- apiGroups: ["kmesh.net"]
  resources: ["kmeshnodeinfos"]
  verbs: ["get", "create", "update", "delete", "list", "watch"]`  in kmesh-rbac.yaml
3.then run
`	kmeshctl secret --key=$(dd if=/dev/urandom count=36 bs=1 2>/dev/null | xxd -p -c 64)`
`	kubectl apply -f deploy/yaml/crd/kmesh.net_kmeshnodeinfos.yaml`
`	helm install kmesh $ROOT_DIR/deploy/charts/kmesh-helm -n kmesh-system --create-namespace --set deploy.kmesh.image.repository=localhost:5000/kmesh \
		--set deploy.kmesh.containers.kmeshDaemonArgs="--mode=dual-engine --enable-bypass=false --monitoring=true --enable-ipsec=true"`

Then the waypoint failed to start and kmesh log as：
`2025-08-12T10:52:18.598497Z     error   citadelclient   failed to sign CSR: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc: i/o timeout"`
`2025-08-12T10:52:18.598874Z     info    citadelclient   recreated connection`
`2025-08-12T10:52:18.598907Z     error   cache   resource:default failed to sign: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc: i/o timeout"`
`2025-08-12T10:52:18.598913Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc: i/o timeout"`

### PR DESCRIPTION
**Pull request by zrggw**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Refactored traffic decrypt marking logic.
Added OutputMark configuration in ipsec_handler.go

If the protocol is ESP, it directly enters the decryption phase to match the xfrm state and then re-enters ingress. If the packet is successfully decrypted, it will be marked as 0xd0. If the packet is not ESP protocol  and has not been decrypted(mark != 0xd0), its mark will be set to 0x0, ensuring it does not match any policy and avoiding the issue described previously.
**Which issue(s) this PR fixes**:
Fixes #1481 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: bpf/kmesh/general/tc_mark_decrypt.c [hunk 1]
```diff
@@ -12,16 +12,34 @@ int tc_mark_decrypt(struct __sk_buff *ctx)
...
     struct nodeinfo *nodeinfo;
     struct tc_info info = {0};
+    __u8 protocol = 0;
+    bool decrypted = false;
+    __u32 mark = 0;
 
     if (parser_tc_info(ctx, &info)) {
         return TC_ACT_OK;
     }
-    nodeinfo = check_remote_manage_by_kmesh(ctx, &info, info.iph->saddr, info.ip6h->saddr.s6_addr32);
```
Comment (hzxuzhonghu) [inline bpf/kmesh/general/tc_mark_decrypt.c:19]: You need to remove the related bpf map  as well

Comment (zrggw) [reply bpf/kmesh/general/tc_mark_decrypt.c:19]: bpf map still need to be used in tc_mark_encrypt.c

Comment (hzxuzhonghu) [reply bpf/kmesh/general/tc_mark_decrypt.c:19]: got it
