### PR TITLE
fix bookinfo issue 553

### LINKED ISSUE #553: kmesh do not support bookinfo example route
**What happened**:
when I start kmesh in ads mode, try bookinfo examples, traffic-management,I don't get the expected result
and kmesh logs:
```
[root@localhost ~]# kubectl logs -f -n kmesh-system kmesh-fwm7k 
cp: cannot create regular file '/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64/kmesh.ko': Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.dep.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.dep.bin.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.alias.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.alias.bin.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.softdep.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.symbols.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.symbols.bin.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.builtin.bin.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.builtin.alias.bin.17.851900.1720665190, 301, 644): Read-only file system
depmod: ERROR: openat(/lib/modules/6.1.19-7.0.0.17.oe2303.x86_64, modules.devname.17.851900.1720665190, 301, 644): Read-only file system
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --bpf-fs-path=\"/sys/fs/bpf\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --cgroup2-path=\"/mnt/kmesh_cgroup2\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --cni-etc-path=\"/etc/cni/net.d\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --conflist-name=\"\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --enable-bpf-log=\"true\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --enable-bypass=\"false\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --enable-mda=\"false\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --enable-secret-manager=\"false\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --help=\"false\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --mode=\"ads\"" subsys=manager
time="2024-07-11T02:33:10Z" level=info msg="FLAG: --plugin-cni-chained=\"true\"" subsys=manager
time="2024-07-11T02:33:13Z" level=info msg="bpf Start successful" subsys=manager
time="2024-07-11T02:33:13Z" level=info msg="start kmesh manage controller successfully" subsys=controller
time="2024-07-11T02:33:13Z" level=info msg="service node sidecar~10.244.1.4~kmesh-fwm7k.kmesh-system~kmesh-system.svc.cluster.local connect to discovery address istiod.istio-system.svc:15012" subsys=controller/config
time="2024-07-11T02:33:13Z" level=info msg="controller Start successful" subsys=manager
time="2024-07-11T02:33:13Z" level=info msg="start write CNI config\n" subsys="cni installer"
time="2024-07-11T02:33:13Z" level=info msg="kmesh cni use chained\n" subsys="cni installer"
time="2024-07-11T02:33:13Z" level=info msg="Copied /usr/bin/kmesh-cni to /opt/cni/bin." subsys="cni installer"
time="2024-07-11T02:33:13Z" level=info msg="kubeconfig either does not exist or is out of date, writing a new one" subsys="cni installer"
time="2024-07-11T02:33:13Z" level=info msg="wrote kubeconfig file /etc/cni/net.d/kmesh-cni-kubeconfig" subsys="cni installer"
time="2024-07-11T02:33:13Z" level=info msg="cni config file: /etc/cni/net.d/10-kindnet.conflist" subsys="cni installer"
time="2024-07-11T02:33:13Z" level=info msg="command Start cni successful" subsys=manager


time="2024-07-11T02:58:59Z" level=info msg="[KMESH] DEBUG: bpf find listener addr=[10.96.42.28:9080]\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] ERR: bpf set sockopt failed! ret:0\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to get cla endpoints ptrs\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to reflush cluster(PassthroughCluster) endpoints\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] DEBUG: bpf find listener addr=[10.96.7.138:9080]\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] ERR: bpf set sockopt failed! ret:0\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to get cla endpoints ptrs\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to reflush cluster(PassthroughCluster) endpoints\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] DEBUG: bpf find listener addr=[10.96.57.127:9080]\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] ERR: bpf set sockopt failed! ret:0\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to get cla endpoints ptrs\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to reflush cluster(PassthroughCluster) endpoints\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] DEBUG: bpf find listener addr=[10.96.57.127:9080]\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[KMESH] ERR: bpf set sockopt failed! ret:0\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to get cla endpoints ptrs\n" subsys=ebpf
time="2024-07-11T02:58:59Z" level=info msg="[CLUSTER] ERR: failed to reflush cluster(PassthroughCluster) endpoints\n" subsys=ebpf

```

I find in route that domains, the domain matching was incorrect. Unable to match the correct host
For example, host in HTTP: `productpage:9080`
And domains in ads config:
```
          {
            "name": "productpage.default.svc.cluster.local:9080",
            "domains": [
              "productpage.default.svc.cluster.local",
              "productpage.default",
              "productpage.default.svc",
              "10.96.81.230"
            ],
            "routes": [
              {
                "name": "default",
                "match": {
                  "prefix": "/"
                },
                "route": {
                  "cluster": "outbound|9080||productpage.default.svc.cluster.local",
                  "retryPolicy": {
                    "numRetries": 2
                  }
                }
              }
            ]
          },
```
Kmesh cannot auto obtain and complete ns information
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

### PR DESCRIPTION
**Pull request by weli-l**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #553

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: bpf/kmesh/ads/include/route_config.h [hunk 1]
```diff
@@ -29,15 +29,16 @@ static inline Route__RouteConfiguration *map_lookup_route_config(const char *rou
...
 static inline int
-virtual_host_match_check(Route__VirtualHost *virt_host, address_t *addr, ctx_buff_t *ctx, struct bpf_mem_ptr *host)
+virtual_host_match_check(Route__VirtualHost *virt_host, char *addr, ctx_buff_t *ctx, struct bpf_mem_ptr *host)
 {
     int i;
     void *domains = NULL;
     void *domain = NULL;
     void *ptr;
     __u32 ptr_length;
+    long target_length = bpf_strnlen(addr, BPF_DATA_MAX_LEN);
```
Comment (hzxuzhonghu) [inline bpf/kmesh/ads/include/route_config.h:39]: if this is a domain, the length can be longer than BPF_DATA_MAX_LEN

Comment (hzxuzhonghu) [reply bpf/kmesh/ads/include/route_config.h:39]: NVM, this is ip str

File: bpf/kmesh/ads/include/route_config.h [hunk 2]
```diff
@@ -311,15 +318,15 @@ static inline char *select_weight_cluster(Route__RouteAction *route_act)
...
-                "select cluster, name:weight %s:%d\n",
-                cluster_name,
-                route_cluster_weight->weight);
-            return cluster_name;
+            break;
         }
     }
+
+    if (cluster_name != NULL) {
+        BPF_LOG(DEBUG, ROUTER_CONFIG, "select cluster, name %s\n", cluster_name);
```
Comment (hzxuzhonghu) [inline bpf/kmesh/ads/include/route_config.h:326]:
```suggestion
        BPF_LOG(DEBUG, ROUTER_CONFIG, "selected cluster: %s\n", cluster_name);
```

File: kernel/ko_src/kmesh/kmesh_parse_protocol_data.h [hunk 3]
```diff
@@ -19,10 +19,10 @@ enum kmesh_l7_msg_type { MSG_UNKNOW = 0, MSG_REQUEST, MSG_MID_REPONSE, MSG_FINAL
 
 #define KMESH_PROTO_TYPE_WIDTH (8)
 
-#define SET_RET_PROTO_TYPE(n, type) (n) = (((n)&0xff00) | ((u32)(type)&0xff))
-#define GET_RET_PROTO_TYPE(n)       ((n)&0xff)
+#define SET_RET_PROTO_TYPE(n, type) (n) = (((n) & 0xff00) | ((u32)(type) & 0xff))
+#define GET_RET_PROTO_TYPE(n)       ((n) & 0xff)
```
Comment (LiZhenCheng9527) [inline kernel/ko_src/kmesh/kmesh_parse_protocol_data.h:23]: Is this an automatic change by clang?
Please reset.

**Review by hzxuzhonghu — DISMISSED** [review]

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
