### PR TITLE
fix: values is not updated in tcp_conn map #1341

### LINKED ISSUE #1341: values is not updated in tcp_conn map
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by yp969803**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: values is not updated in tcp_conn map
**Which issue(s) this PR fixes**:
Fixes #1341

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```NONE

```

### CODE REVIEW

**Comment by yp969803** [comment]
@hzxuzhonghu can u merge this

**Review by hzxuzhonghu — COMMENTED** [review]
Here we need some unit test

**Comment by yp969803** [comment]
@hzxuzhonghu can u merge this pr, i will add unit test in another pr

**Comment by hzxuzhonghu** [comment]
Let's make ut coverage here, we are seeing too many bugs recently

**Comment by yp969803** [comment]
@hzxuzhonghu added ut

**Review by hzxuzhonghu — COMMENTED** [review]
This is causing TestL4Telemetry failure

**Comment by yp969803** [comment]
not getting why the test has failed, I haven't made any significant change which should result in failure

**Comment by yp969803** [comment]
@hzxuzhonghu i think e2e test has some bug which has to be fixed

**Comment by yp969803** [comment]
@hzxuzhonghu you can merge this now !!

File: pkg/controller/telemetry/metric_test.go [hunk 1]
```diff
@@ -1677,3 +1678,96 @@ func TestMetricController_updatePrometheusMetric(t *testing.T) {
 		})
 	}
 }
+
+func TestBuildV4Metric(t *testing.T) {
+	buff := bytes.NewBuffer([]byte{10, 244, 1, 13, 10, 244, 1, 12, 34, 208, 144, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
+		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 96, 46, 224, 144, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
+		0, 3, 0, 0, 0, 147, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 167, 122, 203, 84, 2, 0, 0, 0, 153, 163,
+		210, 202, 232, 184, 0, 0, 64, 30, 158, 31, 235, 184, 0, 0, 0, 0, 0, 0, 150, 158, 0, 0, 19, 0, 0, 0, 0, 0,
+		0, 0, 0, 0, 0, 0, 0, 0, 0, 0})
```
Comment (hzxuzhonghu) [inline pkg/controller/telemetry/metric_test.go:1687]: Ah, this is hard to maintain

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
