### PR TITLE
Fix regression by socket tuple when c/s deployed in same node

### LINKED ISSUE #1370: Metric `sent_bytes` `received_bytes` not consistent with accesslog
**What happened**:

I have been testing the long connection metrics feature. And deployed a websocket client  and a server.

The server sent a message to the client every 1 second.

After a long time, i can see the access log 

```
accesslog: 2025-05-08 07:41:31.436041742 +0000 UTC src.addr=10.244.0.14:49056, src.workload=ws-client, src.namespace=default, dst.addr=10.244.0.11:8080, dst.service=ws-server-service.default.svc.cluster.local, dst.workload=ws-server, dst.namespace=default, start_time=2025-05-08 03:38:34.201259611 +0000 UTC, direction=INBOUND, state=BPF_TCP_ESTABLISHED, sent_bytes=14566, received_bytes=280, packet_loss=0, retransmissions=0, srtt=457us, min_rtt=38us, duration=1.4577234782131e+07ms
accesslog: 2025-05-08 07:41:31.436079898 +0000 UTC src.addr=10.244.0.14:49056, src.workload=ws-client, src.namespace=default, dst.addr=10.244.0.11:8080, dst.service=ws-server-service.default.svc.cluster.local, dst.workload=ws-server, dst.namespace=default, start_time=2025-05-08 03:38:34.201135327 +0000 UTC, direction=OUTBOUND, state=BPF_TCP_ESTABLISHED, sent_bytes=3, received_bytes=29257, packet_loss=0, retransmissions=0, srtt=41600us, min_rtt=40us, duration=1.4577234944571e+07ms
```

And also queried the metrics, they are quite different.

```
kmesh_tcp_connection_received_bytes_total{connection_security_policy="mutual_tls",destination_address="10.244.0.11:8080",destination_app="ws-server",destination_canonical_revision="latest",destination_canonical_service="ws-server",destination_cluster="Kubernetes",destination_pod_address="10.244.0.11",destination_pod_name="ws-server",destination_pod_namespace="default",destination_principal="-",destination_service="ws-server-service.default.svc.cluster.local",destination_service_name="ws-server-service",destination_service_namespace="default",destination_version="latest",destination_workload="ws-server",destination_workload_namespace="default",reporter="destination",request_protocol="tcp",response_flags="-",source_address="10.244.0.14:49056",source_app="ws-client",source_canonical_revision="latest",source_canonical_service="ws-client",source_cluster="Kubernetes",source_principal="-",source_version="latest",source_workload="ws-client",source_workload_namespace="default",start_time="2025-05-08 03:38:34.201259611 +0000 UTC"} 801360
kmesh_tcp_connection_received_bytes_total{connection_security_policy="mutual_tls",destination_address="10.244.0.11:8080",destination_app="ws-server",destination_canonical_revision="latest",destination_canonical_service="ws-server",destination_cluster="Kubernetes",destination_pod_address="10.244.0.11",destination_pod_name="ws-server",destination_pod_namespace="default",destination_principal="-",destination_service="ws-server-service.default.svc.cluster.local",destination_service_name="ws-server-service",destination_service_namespace="default",destination_version="latest",destination_workload="ws-server",destination_workload_namespace="default",reporter="source",request_protocol="tcp",response_flags="-",source_address="10.244.0.14:49056",source_app="ws-client",source_canonical_revision="latest",source_canonical_service="ws-client",source_cluster="Kubernetes",source_principal="-",source_version="latest",source_workload="ws-client",source_workload_namespace="default",start_time="2025-05-08 03:38:34.201135327 +0000 UTC"} 4.3193304e+07
kmesh_tcp_connection_sent_bytes_total{connection_security_policy="mutual_tls",destination_address="10.244.0.11:8080",destination_app="ws-server",destination_canonical_revision="latest",destination_canonical_service="ws-server",destination_cluster="Kubernetes",destination_pod_address="10.244.0.11",destination_pod_name="ws-server",destination_pod_namespace="default",destination_principal="-",destination_service="ws-server-service.default.svc.cluster.local",destination_service_name="ws-server-service",destination_service_namespace="default",destination_version="latest",destination_workload="ws-server",destination_workload_namespace="default",reporter="destination",request_protocol="tcp",response_flags="-",source_address="10.244.0.14:49056",source_app="ws-client",source_canonical_revision="latest",source_canonical_service="ws-client",source_cluster="Kubernetes",source_principal="-",source_version="latest",source_workload="ws-client",source_workload_namespace="default",start_time="2025-05-08 03:38:34.201259611 +0000 UTC"} 2.1417777e+07
kmesh_tcp_connection_sent_bytes_total{connection_security_policy="mutual_tls",destination_address="10.244.0.11:8080",destination_app="ws-server",destination_canonical_revision="latest",destination_canonical_service="ws-server",destination_cluster="Kubernetes",destination_pod_address="10.244.0.11",destination_pod_name="ws-server",destination_pod_namespace="default",destination_principal="-",destination_service="ws-server-service.default.svc.cluster.local",destination_service_name="ws-server-service",destination_service_namespace="default",destination_version="latest",destination_workload="ws-server",destination_workload_namespace="default",reporter="source",request_protocol="tcp",response_flags="-",source_address="10.244.0.14:49056",source_app="ws-client",source_canonical_revision="latest",source_canonical_service="ws-client",source_cluster="Kubernetes",source_principal="-",source_version="latest",source_workload="ws-client",source_workload_namespace="default",start_time="2025-05-08 03:38:34.201135327 +0000 UTC"} 8586
```

And the workload sent bytes is also not consistent

```
kmesh_tcp_workload_sent_bytes_total{connection_security_policy="mutual_tls",destination_app="ws-server",destination_canonical_revision="latest",destination_canonical_service="ws-server",destination_cluster="Kubernetes",destination_pod_address="10.244.0.11",destination_pod_name="ws-server",destination_pod_namespace="default",destination_principal="-",destination_version="latest",destination_workload="ws-server",destination_workload_namespace="default",reporter="destination",request_protocol="tcp",response_flags="-",source_app="ws-client",source_canonical_revision="latest",source_canonical_service="ws-client",source_cluster="Kubernetes",source_principal="-",source_version="latest",source_workload="ws-client",source_workload_namespace="default"} 2.2251539e+07
kmesh_tcp_workload_sent_bytes_total{connection_security_policy="mutual_tls",destination_app="ws-server",destination_canonical_revision="latest",destination_canonical_service="ws-server",destination_cluster="Kubernetes",destination_pod_address="10.244.0.11",destination_pod_name="ws-server",destination_pod_namespace="default",destination_principal="-",destination_version="latest",destination_workload="ws-server",destination_workload_namespace="default",reporter="source",request_protocol="tcp",response_flags="-",source_app="ws-client",source_canonical_revision="latest",source_canonical_service="ws-client",source_cluster="Kubernetes",source_principal="-",source_version="latest",source_workload="ws-client",source_workload_namespace="default"} 1.2536987285488e+13
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1370

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Fix https://github.com/kmesh-net/kmesh/issues/1370

**Comment by yp969803** [comment]
unit tests are also be updated

**Comment by hzxuzhonghu** [comment]
@yp969803 can you help add ut coverage for same src/dst but different direction case after this pr

File: pkg/controller/telemetry/metric_test.go [hunk 1]
```diff
@@ -1687,10 +1687,11 @@ func TestBuildV4Metric(t *testing.T) {
 		0, 0, 0, 0, 0, 0, 0, 0, 0, 0})
 	data := requestMetric{
 		conSrcDstInfo: connectionSrcDst{
-			src:     [4]uint32{218231818, 0, 0, 0},
-			dst:     [4]uint32{201454602, 0, 0, 0},
-			srcPort: 53282,
-			dstPort: 8080,
+			src:       [4]uint32{218231818, 0, 0, 0},
+			dst:       [4]uint32{201454602, 0, 0, 0},
+			direction: 2,
```
Comment (LiZhenCheng9527) [inline pkg/controller/telemetry/metric_test.go:1692]:
```suggestion
			direction: constants.OUNBOUND,
```
more intuitive

File: pkg/controller/telemetry/metric.go [hunk 2]
```diff
@@ -502,156 +502,158 @@ func (m *MetricController) Run(ctx context.Context, mapOfTcpInfo *ebpf.Map) {
...
+		return reqMetric, err
 	}
-	data.conSrcDstInfo.src = connectData.SrcAddr
-	data.conSrcDstInfo.dst = connectData.DstAddr
-	data.direction = connectData.Direction
-	data.conSrcDstInfo.dstPort = connectData.DstPort
-	data.conSrcDstInfo.srcPort = connectData.SrcPort
+	reqMetric.conSrcDstInfo.src = rawStats.SrcAddr
+	reqMetric.conSrcDstInfo.dst = rawStats.DstAddr
+	reqMetric.conSrcDstInfo.direction = rawStats.Direction
```
Comment (YaoZengzeng) [inline pkg/controller/telemetry/metric.go:603]: Is this the root cause of the problem? Too many renames swamping critical changes.

Comment (hzxuzhonghu) [reply pkg/controller/telemetry/metric.go:603]: right
