### PR TITLE
Fix kmesh manage, especially after kmesh restart, old xdp prog maybe …

### LINKED ISSUE #1346: old xdp linked after kmesh daemon restart
**What happened**:

After kmesh daemon restarted, i found the authz does not take effect

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
…linked because of the event order

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Fix #1346

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/controller/manage/manage_controller.go [hunk 1]
```diff
@@ -138,6 +141,9 @@ func (c *KmeshManageController) handlePodAdd(obj interface{}) {
 
 	namespace, err := c.namespaceLister.Get(newPod.Namespace)
 	if err != nil {
+		if apierrors.IsNotFound(err) {
+			return
```
Comment (YaoZengzeng) [inline pkg/controller/manage/manage_controller.go:145]: Is there any change from before? Other than one less line of logging.

Comment (hzxuzhonghu) [reply pkg/controller/manage/manage_controller.go:145]: ?

**Comment by hzxuzhonghu** [comment]
cc @Kuromesi
