### PR TITLE
output kmesh log when e2e test failed

### LINKED ISSUE #1390: Print kmesh daemon logs when e2e tests fail
**What would you like to be added**:

Print kmesh daemon logs when e2e tests fail, especially Kmesh daemon in the worker node

**Why is this needed**:

Because there are always some flaky cases that are very difficult to reproduce locally, but always appear in CI.

If we can print the log of Kmesh daemon, it will be very helpful for our debugging.

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1390

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu ptal

File: test/e2e/run_test.sh [hunk 1]
```diff
@@ -11,6 +11,8 @@ DEFAULT_KIND_IMAGE="kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba
 
 ISTIO_VERSION=${ISTIO_VERSION:-"1.22.0"}
 
+LOGFILE="kmesh_daemon.log"
```
Comment (hzxuzhonghu) [inline test/e2e/run_test.sh:14]: We cannot see it once CI job running failed

File: test/e2e/run_test.sh [hunk 2]
```diff
@@ -283,9 +375,17 @@ if [[ -z ${SKIP_SETUP:-} ]]; then
...
+
+capture_pod_logs &
+
 cmd="go test -v -tags=integ $ROOT_DIR/test/e2e/... -istio.test.kube.loadbalancer=false ${PARAMS[*]}"
 
-bash -c "$cmd"
+bash -c "$cmd" || {
+	cat $LOGFILE
+	rm $LOGFILE
+	exit 1
```
Comment (hzxuzhonghu) [inline test/e2e/run_test.sh:387]: why exit without cleaning up. I think failure does not mean not cleaning up, they are orthogonal

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu updated
