### PR TITLE
handle service and workload conflicts in the frontend map

### LINKED ISSUE #1149: Services and workloads have conflicts in the frontend map
**What happened**:
The frontend map storages the upstream information about the service and workload. Key is the IP address of service and workload.
https://github.com/kmesh-net/kmesh/blob/7425245e40171db1759198cc9ced8d20cc0a5d66/pkg/controller/workload/bpfcache/frontend.go#L24-L28
The updated workload information will overwrite the service information. This causes kmesh cannot govern traffic to this service.

But such a handler has a bug if the ip addresses of service and workload are the same. 

**What you expected to happen**:

Dealing with this conflict.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version: 0.5.0
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`): Duel-Engine Mode
- Istio version: 1.24.1
- Kernel version: 5.15
- Others:

### PR DESCRIPTION
**Pull request by LiZhenCheng9527**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
handle service and workload conflicts in the frontend map of serviceEntry cases.
**Which issue(s) this PR fixes**:
Fixes #1149

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/controller/workload/workload_processor.go [hunk 1]
```diff
@@ -426,14 +425,31 @@ func (p *Processor) updateWorkloadInFrontendMap(workload *workloadapi.Workload)
 	log.Debugf("updateWorkloadInFrontendMap: workload %s, backendUid: %v", workload.GetUid(), backendUid)
 
 	for _, ip := range workload.GetAddresses() {
+		svc := p.getServiceByAddress(ip)
+		if svc != nil {
+			// If the service is found in serviceCache based on the ip address of the workload.
+			// we don't update the workload in the frontend map.
+			// This occurs in the serviceEntry.
+			log.Debugf("workload: %v and service: %v have same ip address: %v", workload.Uid, svc.ResourceName(), ip)
+			return nil
```
Comment (hzxuzhonghu) [inline pkg/controller/workload/workload_processor.go:434]: continue

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
