### PR TITLE
fix kmeshctl version report error

### LINKED ISSUE #1364: kmeshctl v1.1.0-alpha showed unexpected version
**What happened**:
 
```
kmeshctl version
client version: v1.1.0-alpha-80ae5efc927591a73d6b93efb5865d22de2868b4
kmesh-daemon version: 
```

**What you expected to happen**:

`client version: v1.1.0-alpha` is actually expected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by LiZhenCheng9527**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1364 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: ctl/version/version.go [hunk 1]
```diff
@@ -129,3 +139,11 @@ func getVersion(client kube.CLIClient, podName string) (version version.Info) {
 
 	return
 }
+
+// match release version vx.y.z-(alpha)
+func stringMatch(str string) bool {
+	pattern := `^v\d+\.\d+\.\d+(-[a-zA-Z0-9]+)?$`
```
Comment (hzxuzhonghu) [inline ctl/version/version.go:145]: Does it support matching v1.1.1-alpha.0?

Comment (LiZhenCheng9527) [reply ctl/version/version.go:145]: No. Add a unit test to validata it.

Comment (hzxuzhonghu) [reply ctl/version/version.go:145]: https://semver.org/ FYI, i think we should support it

Comment (LiZhenCheng9527) [reply ctl/version/version.go]: The regular expression was modified to handle this case.

**Review by hzxuzhonghu — APPROVED** [review]
approve first for our usage though i think it does not cover all cases well
/lgtm
