### PR TITLE
fix: Updating connOpened metric for the conn report at intervals #1307

### LINKED ISSUE #1307: Updating connOpened metric for the conn report at intervals
**What happened**:
```
func (m *MetricController) updateWorkloadMetricCache(data requestMetric, labels workloadMetricLabels) {
	v, ok := m.workloadMetricCache[labels]
	if ok {
		if data.state == TCP_ESTABLISHED {
			v.WorkloadConnOpened = v.WorkloadConnOpened + 1
		}
```
Updating long-conn open metric for  conn report at intervals

**What you expected to happen**:
It should only update for the first report

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by yp969803**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Fixing updating connOpened metric for the conn report at intervals, added unit test to confirm the change
**Which issue(s) this PR fixes**:
Fixes #1307

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No

```release-note

```

### CODE REVIEW

**Comment by yp969803** [comment]
@hzxuzhonghu can you merge this

**Comment by hzxuzhonghu** [comment]
I am not sure what it is doing from the descroption. Let me take a look at the code

File: pkg/controller/telemetry/metric.go [hunk 1]
```diff
@@ -422,9 +423,9 @@ func (m *MetricController) Run(ctx context.Context, mapOfTcpInfo *ebpf.Map) {
 
 			m.mutex.Lock()
 			if m.EnableWorkloadMetric.Load() {
-				m.updateWorkloadMetricCache(data, workloadLabels)
+				m.updateWorkloadMetricCache(data, workloadLabels, tcp_conns)
```
Comment (hzxuzhonghu) [inline pkg/controller/telemetry/metric.go:426]: can you change tcp_conns to tcpConns, which golang idiomatic

File: pkg/controller/telemetry/metric.go [hunk 2]
```diff
@@ -704,10 +727,10 @@ func (m *MetricController) updateWorkloadMetricCache(data requestMetric, labels
 	}
 }
 
-func (m *MetricController) updateServiceMetricCache(data requestMetric, labels serviceMetricLabels) {
+func (m *MetricController) updateServiceMetricCache(data requestMetric, labels serviceMetricLabels, tcp_conns map[connectionSrcDst]connMetric) {
 	v, ok := m.serviceMetricCache[labels]
 	if ok {
-		if data.state == TCP_ESTABLISHED {
+		if data.state == TCP_ESTABLISHED && tcp_conns[data.conSrcDstInfo].totalReports == 1 {
```
Comment (hzxuzhonghu) [inline pkg/controller/telemetry/metric.go:733]: Understood

**Review by hzxuzhonghu — COMMENTED** [review]
/lgtm
/approve
