### PR TITLE
rfac: outputAccesslog func to skip accesslog at conn establishment

### LINKED ISSUE #1375: Do not output accesslog at conn start
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kmesh version:
- Kmesh mode(kmesh has `Kernel-Native Mode` and `Duel-Engine Mode`):
- Istio version:
- Kernel version:
- Others:

### PR DESCRIPTION
**Pull request by yp969803**
**What type of PR is this?**
=/kind enhancement

**What this PR does / why we need it**:
outputAccesslog func to skip accesslog at conn establishment

**Which issue(s) this PR fixes**:
Fixes #1375

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by yp969803** [comment]
@hzxuzhonghu can u review, it is more better approach

**Comment by yp969803** [comment]
also i haved fixed the type TCP_CLOSTED

File: pkg/controller/telemetry/metric.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ const (
 
 	DEFAULT_UNKNOWN = "-"
 
-	LONG_CONN_METRIC_THRESHOLD = uint64(5 * time.Second)
+	LONG_CONN_METRIC_THRESHOLD = uint64(30 * time.Second)
```
Comment (LiZhenCheng9527) [inline pkg/controller/telemetry/metric.go:51]: Is there any basis for the threshold modification to 30s?

Comment (yp969803) [reply pkg/controller/telemetry/metric.go:51]: The duration was initially set to 30 seconds, but @hzxuzhonghu reduced it to 5 seconds. In Prometheus, metrics are scraped at fixed intervals, with the maximum scrape interval being 15 seconds. For short-lived connections lasting less than 15 seconds, a connectionMetric might be created and deleted before it can be scraped. This results in unnecessary computation, as the metric is never captured by the user.

Comment (yp969803) [reply pkg/controller/telemetry/metric.go]: i have changed it to 5

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm
